# Generated by Django 4.0 on 2022-01-15 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, null=True)),
                ('product_description', models.CharField(max_length=1000, null=True)),
                ('product_prize', models.FloatField(max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='useraddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, null=True)),
                ('house', models.CharField(max_length=200, null=True)),
                ('post_code', models.IntegerField(max_length=200, null=True)),
                ('city', models.CharField(max_length=200, null=True)),
                ('state', models.CharField(max_length=200, null=True)),
                ('country', models.CharField(max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'useradress',
                'verbose_name_plural': 'useradresss',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
