# Generated by Django 4.0 on 2022-01-15 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_useraddress_user_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.AlterModelOptions(
            name='useraddress',
            options={},
        ),
        migrations.AlterModelTable(
            name='product',
            table=None,
        ),
        migrations.AlterModelTable(
            name='useraddress',
            table=None,
        ),
    ]
