# Generated by Django 4.0 on 2022-01-15 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_alter_product_options_alter_useraddress_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useraddress',
            options={'managed': True, 'verbose_name': 'useradress', 'verbose_name_plural': 'useradresss'},
        ),
        migrations.RenameField(
            model_name='useraddress',
            old_name='house',
            new_name='house_address',
        ),
        migrations.AlterModelTable(
            name='useraddress',
            table='',
        ),
    ]
