# Generated by Django 4.0 on 2022-01-15 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'managed': True, 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AddField(
            model_name='product',
            name='category_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.category'),
        ),
        migrations.AlterModelTable(
            name='product',
            table='',
        ),
    ]
