# Generated by Django 4.0 on 2022-01-15 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_alter_product_options_product_category_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='category_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_description',
            field=models.CharField(default=0, max_length=1000),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_prize',
            field=models.FloatField(default=0, max_length=200),
        ),
    ]
