# Generated by Django 4.0 on 2022-01-17 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_alter_product_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.PositiveIntegerField(max_length=4)),
            ],
            options={
                'verbose_name': 'Sms',
                'verbose_name_plural': 'Smss',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
