# Generated by Django 4.0 on 2022-01-17 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_sms_alter_product_product_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sms',
            options={},
        ),
        migrations.AddField(
            model_name='product',
            name='product_image1',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_image2',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_image3',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterModelTable(
            name='sms',
            table=None,
        ),
    ]
