# Generated by Django 4.0 on 2022-01-17 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_alter_sms_options_product_product_image1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_image1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_image2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_image3',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_description',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
