# Generated by Django 4.0 on 2022-01-18 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0015_product_product_image1_product_product_image2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Icon_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('Logo_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('Banner_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('Footer_image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
