# Generated by Django 4.0 on 2022-01-19 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0016_design'),
    ]

    operations = [
        migrations.RenameField(
            model_name='design',
            old_name='Banner_image',
            new_name='Banner_image1',
        ),
        migrations.AddField(
            model_name='design',
            name='Banner_image2',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='design',
            name='Banner_image3',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
