# Generated by Django 4.0 on 2022-01-25 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0023_customer_order_orderitem_shippingaddress_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='useraddress',
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.usercreation'),
        ),
    ]
