# Generated by Django 4.0 on 2022-01-26 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0024_rename_customer_useraddress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_prize',
            field=models.IntegerField(max_length=200, null=True),
        ),
    ]
