# Generated by Django 4.0 on 2022-01-26 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0025_alter_product_product_prize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_prize',
            field=models.FloatField(max_length=200, null=True),
        ),
    ]
