# Generated by Django 4.0 on 2022-01-31 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0029_useraddress_user_alter_orderitem_quantity_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useraddress',
            options={},
        ),
        migrations.AlterModelTable(
            name='useraddress',
            table=None,
        ),
    ]
