# Generated by Django 4.0 on 2022-02-01 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0033_customeradress_delete_useraddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeradress',
            name='phone_number',
            field=models.IntegerField(max_length=50),
        ),
    ]
