# Generated by Django 4.0 on 2022-02-01 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0035_alter_customeradress_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeradress',
            name='phone_number',
            field=models.CharField(max_length=99),
        ),
    ]
