# Generated by Django 4.0 on 2022-02-03 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0037_order_product_alter_order_transcation_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='product',
            new_name='orderproduct',
        ),
    ]
