# Generated by Django 4.0 on 2022-02-03 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0040_order_product_alter_order_transcation_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
