# Generated by Django 4.0 on 2022-02-03 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0041_order_payment_method'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='product',
            new_name='order_product',
        ),
    ]
