# Generated by Django 4.0 on 2022-02-03 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0042_rename_product_order_order_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShippingAddress',
        ),
    ]
