# Generated by Django 4.0 on 2022-02-03 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0043_delete_shippingaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(max_length=10),
        ),
    ]
