# Generated by Django 4.0 on 2022-02-03 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0044_alter_order_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_method',
        ),
    ]
