# Generated by Django 4.0 on 2022-02-03 15:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0049_alter_product_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ordered', models.DateField(auto_now_add=True)),
                ('complete', models.BooleanField(blank=True, default=False, null=True)),
                ('transcation_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('Customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.usercreation')),
                ('order_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.product')),
            ],
        ),
    ]
