# Generated by Django 4.0 on 2022-02-03 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0050_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.customeradress'),
        ),
    ]
