# Generated by Django 4.0 on 2022-02-03 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0052_remove_order_order_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.product'),
        ),
    ]
