# Generated by Django 4.0 on 2022-02-03 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0053_order_order_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
