# Generated by Django 4.0 on 2022-02-03 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0054_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.usercreation'),
        ),
    ]
