# Generated by Django 4.0 on 2022-02-03 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0056_order_total_prize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_prize',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
