# Generated by Django 4.0 on 2022-02-03 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0057_alter_order_total_prize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_prize',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
