# Generated by Django 4.0 on 2022-02-04 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0058_alter_order_total_prize'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='complete',
        ),
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Return', 'Return'), ('Canceled', 'Canceled'), ('Packed', 'Packed'), ('On the way', 'On the way'), ('Accepted', 'Accepted'), ('Delivered', 'Delivered')], default='pending', max_length=100),
        ),
    ]
