# Generated by Django 4.0 on 2022-02-04 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0059_remove_order_complete_order_quantity_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Canceled', 'Canceled'), ('Accepted', 'Accepted'), ('Return', 'Return'), ('Delivered', 'Delivered'), ('On the way', 'On the way'), ('Packed', 'Packed')], default='pending', max_length=100),
        ),
    ]
