# Generated by Django 4.0 on 2022-02-04 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0060_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_ordered',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Canceled', 'Canceled'), ('Packed', 'Packed'), ('Return', 'Return'), ('On the way', 'On the way'), ('Accepted', 'Accepted')], default='pending', max_length=100),
        ),
    ]
