# Generated by Django 4.0 on 2022-02-06 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0062_alter_order_date_ordered_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Canceled', 'Canceled'), ('Accepted', 'Accepted'), ('Return', 'Return'), ('Delivered', 'Delivered'), ('On the way', 'On the way'), ('Packed', 'Packed')], default='Pending', max_length=100),
        ),
    ]
