# Generated by Django 4.0 on 2022-02-08 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0064_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('On the way', 'On the way'), ('Return', 'Return'), ('Canceled', 'Canceled'), ('Accepted', 'Accepted'), ('Packed', 'Packed')], default='Processing', max_length=100),
        ),
    ]
