# Generated by Django 4.0 on 2022-02-09 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0069_coupen_delete_sms_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='digital',
        ),
        migrations.AddField(
            model_name='coupen',
            name='Coupen_offer',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='coupen',
            name='Coupencode',
            field=models.IntegerField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='Coupen_offer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.coupen'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Canceled', 'Canceled'), ('Return', 'Return'), ('Packed', 'Packed')], default='Processing', max_length=100),
        ),
    ]
