# Generated by Django 4.0 on 2022-02-09 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0070_remove_product_digital_coupen_coupen_offer_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.AlterField(
            model_name='coupen',
            name='Coupen_offer',
            field=models.IntegerField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Packed', 'Packed'), ('Delivered', 'Delivered'), ('Canceled', 'Canceled'), ('Return', 'Return')], default='Processing', max_length=100),
        ),
        migrations.AlterModelTable(
            name='product',
            table=None,
        ),
    ]
