# Generated by Django 4.0 on 2022-02-09 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0071_alter_product_options_alter_coupen_coupen_offer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='Coupen_offer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.coupen'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Canceled', 'Canceled'), ('Delivered', 'Delivered'), ('Return', 'Return'), ('Packed', 'Packed')], default='Processing', max_length=100),
        ),
    ]
