# Generated by Django 4.0 on 2022-02-10 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0072_category_coupen_offer_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='Coupen_offer',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Coupen_offer',
        ),
        migrations.AddField(
            model_name='category',
            name='Category_offer',
            field=models.IntegerField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_offer',
            field=models.IntegerField(default=0, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Packed', 'Packed'), ('Delivered', 'Delivered'), ('Canceled', 'Canceled'), ('Return', 'Return')], default='Processing', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_prize',
            field=models.IntegerField(max_length=200, null=True),
        ),
    ]
