# Generated by Django 4.0 on 2022-02-10 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0074_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercreation',
            name='coupen',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Return', 'Return'), ('Canceled', 'Canceled'), ('Delivered', 'Delivered'), ('Packed', 'Packed')], default='Processing', max_length=100),
        ),
    ]
