# Generated by Django 4.0 on 2022-02-14 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0081_alter_order_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Wishlist',
            new_name='MyWishList',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Packed', 'Packed'), ('Canceled', 'Canceled'), ('Return', 'Return'), ('Delivered', 'Delivered')], default='Processing', max_length=100),
        ),
    ]
